trigger:
  branches:
    include:
    - master
  paths:
    include:
    - environment_setup/arm-templates/*
pr:
  branches:
    include:
    - master
  paths:
    include:
    - environment_setup/arm-templates/*

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: devopsforai-aml-vg


steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'AzureResourceConnection'
    subscriptionId: 'b70d598f-6ad7-4a83-b960-927dfe48405f'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'ml-ops'
    location: 'East US'
    templateLocation: 'Linked artifact'
    csmFile: '/environment_setup/arm-templates/cloud-environment.json'
    overrideParameters: '-baseName $(BASE_NAME) -location $(LOCATION) -workspace $(WORKSPACE_NAME)'
    deploymentMode: 'Incremental'
  displayName: 'Deploy MLOps resources to Azure'

